# Generated by Django 3.2.7 on 2021-11-03 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfilesView',
            new_name='UserProfile',
        ),
    ]
